version: "3.8"

services:
  db:
    image: mysql:8
    container_name: "db_mysql"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    # command: --default-authentication-plugin=mysql_native_password

  api:
    container_name: "boilerplate"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/app/

networks:
  default:
volumes:
  db_data:
