version: "3.8"

services:
  # api:
  #   container_name: "api_boilerplate"
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "1337:1337"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - .:/app

  db:
    image: mysql:8
    container_name: "db_mysql"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  db_data:
